### ISSUE TITLE
Add Support for MongoID

### ISSUE THREAD

**Issue by robertomiranda** [robertomiranda/has_secure_token#1]

**Comment by robertomiranda** [comment]
This will be a back-port from rails 5, so for the moment I'm going dismiss this

**Comment by tilsammans** [comment]
@robertomiranda seems to me if require activemodel and not activerecord it's automatically compatible with mongoid. Would you be up for that or rather have a fork that uses activemodel?

**Comment by robertomiranda** [comment]
@tilsammans sounds good to me a fork, in order to keep this gem as a back-port, wdyt about this name `active_model_secure_token`? :grin:

**Comment by tilsammans** [comment]
Verbose, descriptive, I love it! :)

https://github.com/Sign2Pay/has_secure_token

I will work on it in the coming weeks.
