### ISSUE TITLE
Is it possible to regenerate the token?

### ISSUE THREAD

**Issue by VivianaGarces** [robertomiranda/has_secure_token#12]
Hi, I wanna know if it's possible to create a new token. I saw the test file and there was a regenerate token function, can I use it like user.regenerate_token? thanks in advance

**Comment by robertomiranda** [comment]
Sure, you can this method returns a boolean, when is true means that new token was generated. So the next time when you hit the token column will be have a different value

**Comment by VivianaGarces** [comment]
Do I need to override some method in my users.rb?, when I try to use it I get an Unknow method error

**Comment by robertomiranda** [comment]
Could you paste an example code??



—

**Comment by VivianaGarces** [comment]
Sure, I'm working with an API and this is the part where I use the method (and the beginning of my controller)
```
module API
  class SessionsController < ApplicationController
    skip_before_filter :authorize
    skip_before_filter :verify_authenticity_token
def create
      user = User.find_by_login_user_name(params[:login_user_name])
      if user and user.authenticate(params[:password])
        if user.fecha_desactivacion > Date.today && user.login_user_name!="admin"
          user.regenerate_token
          user.save
          render json:  user, status: 200
```

In user.rb the only thing I wrote for the token was `has_secure_token  :auth_token`

**Comment by robertomiranda** [comment]
ah, well the regenerate methods takes its names from the token attributes `regenerate_<attribute_name>`.
So in your example you need to use `user.regenerate_ auth_token`

**Comment by VivianaGarces** [comment]
Sorry for the delay... It worked!. To clarify and for future references the method is without the space `user.regenerate_auth_token`
