### ISSUE TITLE
NoMethodError: undefined method `has_secure_token' for #<Class:0x007fab3cc8f598>

### ISSUE THREAD

**Issue by fbrix** [robertomiranda/has_secure_token#3]
After installing the gem and putting `has_secure_token :uid` into my model it says in rails console:

```
$ ImageSearch.all
$ NoMethodError: undefined method `has_secure_token' for #<Class:0x007fab3cc8f598>
  ........
```

Am I missing something?

Thanks in advance!

**Comment by lastobelus** [comment]
@fbrix: Is it possible you didn't restart spring after installing the gem? That would result in the error you got.
